package model;

import com.sun.org.apache.regexp.internal.RE;
import domainapp.basics.exceptions.ConstraintViolationException;
import domainapp.basics.model.meta.DAssoc;
import domainapp.basics.model.meta.DAttr;
import domainapp.basics.model.meta.DOpt;
import domainapp.basics.util.Tuple;

public abstract class Hero {
    @DAttr(name = "id", type = DAttr.Type.String, mutable = false, id = true, auto = true, length = 15)
    private String id;
    @DAttr(name = "name", type = DAttr.Type.String, mutable = true, length = 10)
    private String name;
    @DAttr(name = "level", type = DAttr.Type.Integer, mutable = false, min = 1, max = 100)
    private Integer level;
    @DAttr(name = "attack", type = DAttr.Type.Integer, mutable = false, min = 10, max = 1000)
    private Integer attack;
    @DAttr(name = "defense", type = DAttr.Type.Integer, mutable = false, min = 10, max = 1000)
    private Integer defense;
    @DAttr(name = "hp", type = DAttr.Type.Integer, mutable = false, min = 0, max = 1000)
    private Integer hp;
    @DAttr(name = "strength", type = DAttr.Type.Integer, mutable = false, min = 0, max = 100)
    private int strength;
    @DAttr(name = "dexterity", type = DAttr.Type.Integer, mutable = false, min = 0, max = 100)
    private int dexterity;
    @DAttr(name = "intelligent", type = DAttr.Type.Integer, mutable = false, min = 0, max = 100)
    private int intelligent;



    @DAttr(name = "weapons", type = DAttr.Type.Domain, length = 10, optional = false)
    @DAssoc(ascName = "hero-has-weapon", role = "hero", ascType = DAssoc.AssocType.One2One, endType = DAssoc.AssocEndType.One,
            associate = @DAssoc.Associate(type = Weapons.class, cardMin = 1, cardMax = 1), dependsOn = true)
    private Weapons weapons;
    @DAttr(name = "armors", type = DAttr.Type.Domain, length = 10, optional = false)
    @DAssoc(ascName = "hero-has-armor", role = "hero", ascType = DAssoc.AssocType.One2One, endType = DAssoc.AssocEndType.One,
            associate = @DAssoc.Associate(type = Armors.class, cardMin = 1, cardMax = 1), dependsOn = true)
    private Armors armors;

    @DAttr(name = "report", type = DAttr.Type.Domain, length = 5, optional = false)
    @DAssoc(ascName = "report-has-heroes", role = "heroes",
            ascType = DAssoc.AssocType.One2Many, endType = DAssoc.AssocEndType.Many,
            associate = @DAssoc.Associate(type = Report.class, cardMin = 1, cardMax = 1), dependsOn = false)
    private Report report;

    private static int idCounter = 0;

    @DOpt(type = DOpt.Type.AutoAttributeValueSynchroniser)
    public static void updateAutoGeneratedValue (
            DAttr attrib,
            Tuple derivingValue,
            Object minVal,
            Object maxVal) throws ConstraintViolationException {
        if (minVal != null && maxVal != null) {
            if (attrib.name().equals("id")) {
                int maxIdVal = Integer.parseInt(maxVal.toString().replaceAll("[^\\d.]", ""));
                if (maxIdVal > idCounter)
                    idCounter = maxIdVal;
            }
        }
    }

    //    protected static int nextId(int currID) {
//        if (currID == 0) {
//            idCounter++;
//            return idCounter;
//        } else {
//            if (currID > idCounter)
//                idCounter = currID;
//            return currID;
//        }
//    }

    private String nextID(String currId) {
        if (currId == null) {
            idCounter++;
            if (this instanceof Mage) {
                return Mage.class.getSimpleName() +  idCounter;
            } else if (this instanceof Warrior) {
                return Warrior.class.getSimpleName() +  idCounter;
            } else if (this instanceof Rogue) {
                return Rogue.class.getSimpleName() + idCounter;
            }
        } else {
            int num = 0;
            if (this instanceof Mage) {
                num = Integer.parseInt(currId.substring(4));
            } else if (this instanceof Warrior) {
                num = Integer.parseInt(currId.substring(7));
            } else if (this instanceof Rogue) {
                num = Integer.parseInt(currId.substring(5));
            }
            if (num > idCounter) {
                idCounter = num;
            }

        }
        return currId;
    }
    public Hero(String id, String name, Integer level, Integer attack, Integer defense, Integer hp, Integer strength,
                   Integer dexterity, Integer intelligent, Weapons weapons, Armors armors, Report report) {

        this.id = nextID(id);
        this.name = name;
        this.level = level;
        this.attack = attack;
        this.defense = defense;
        this.hp = hp;
        this.strength = strength;
        this.dexterity = dexterity;
        this.intelligent = intelligent;
        this.weapons = weapons;
        this.armors = armors;
        this.report = report;
        // idCounter++;
    }

    public Hero(String name, Integer level, Integer attack, Integer defense, Integer hp, Integer strength, Integer dexterity,
                Integer intelligent, Weapons weapons, Armors armors, Report report) {
        this(null, name, 1, 10, 10, 100,0,0,0, weapons, armors,report);
    }

    public Hero(String name, Weapons weapons, Armors armors, Report report) {
        this(null, name, 1, 10, 10, 100,0,0,0, weapons, armors, report);
    }



    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public int getHp() {
        return hp;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getLevel() {
        return level;
    }

    public void setLevel(int level) {
        attack = attack - this.level + level;
        defense = defense - this.level + level;
        this.level = level;
    }

    public String tauntLine() {
        return "I am ready for anything";
    }


    public int getAttack() {
        return attack;
    }

    public int getDefense() {
        return defense;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public void setAttack(Integer attack) {
        this.attack = attack;
    }

    public void setDefense(Integer defense) {
        this.defense = defense;
    }

    public void setHp(Integer hp) {
        this.hp = hp;
    }

    public int getStrength() {
        return strength;
    }

    public void setStrength(int strength) {
        this.strength = strength;
    }

    public int getDexterity() {
        return dexterity;
    }

    public void setDexterity(int dexterity) {
        this.dexterity = dexterity;
    }

    public int getIntelligent() {
        return intelligent;
    }

    public void setIntelligent(int intelligent) {
        this.intelligent = intelligent;
    }

    public Weapons getWeapons() {
        return weapons;
    }

    public void setWeapons(Weapons weapons) {
        this.weapons = weapons;
        this.strength += weapons.getStrength();
        this.dexterity += weapons.getDexterity();
        this.intelligent += weapons.getIntelligent();

    }

    public Armors getArmors() {
        return armors;
    }

    public void setArmors(Armors armors) {
        this.armors = armors;
        this.strength += armors.getStrength();
        this.dexterity += armors.getDexterity();
        this.intelligent += armors.getIntelligent();
    }

    public void update(Weapons weapons, Armors armors){
        setWeapons(weapons);
        setArmors(armors);
    }

    public Report getReport() {
        return report;
    }

    public void setReport(Report report) {
        this.report = report;
    }
}
