package model;

import com.sun.org.apache.regexp.internal.RE;
import domainapp.basics.exceptions.ConstraintViolationException;
import domainapp.basics.model.meta.DAssoc;
import domainapp.basics.model.meta.DAttr;
import domainapp.basics.model.meta.DOpt;
import domainapp.basics.util.Tuple;

public abstract class Weapons {
    @DAttr(name = "id", type = DAttr.Type.String, mutable = false, id = true, auto = true)
    protected String id;
    @DAttr(name = "name", type = DAttr.Type.String, mutable = true, length = 10)
    protected String name;
    @DAttr(name = "strength", type = DAttr.Type.Integer, mutable = false, min = 1, max = 20)
    protected Integer strength;
    @DAttr(name = "dexterity", type = DAttr.Type.Integer, mutable = false, min = 1, max = 20)
    protected Integer dexterity;
    @DAttr(name = "intelligent", type = DAttr.Type.Integer, mutable = false, min = 1, max = 20)
    protected Integer intelligent;
    @DAttr(name = "hero", type = DAttr.Type.Domain, length = 10, optional = true)
    @DAssoc(ascName = "hero-has-weapon", role = "weapon", ascType = DAssoc.AssocType.One2One, endType = DAssoc.AssocEndType.One,
            associate = @DAssoc.Associate(type = Hero.class, cardMin = 1, cardMax = 1), dependsOn = true)
    protected Hero hero;
    private static int idCounter;

    @DOpt(type = DOpt.Type.AutoAttributeValueSynchroniser)
    public static void updateAutoGeneratedValue(
            DAttr attrib,
            Tuple derivingValue,
            Object minVal,
            Object maxVal) throws ConstraintViolationException {
        if (minVal != null && maxVal != null) {
            if (attrib.name().equals("id")) {
                int maxIdVal = Integer.parseInt(maxVal.toString().replaceAll("[^\\d.]", ""));
                if (maxIdVal > idCounter)
                    idCounter = maxIdVal;
            }
        }
    }

    protected static String nextId(String id) {

        idCounter++;
        return id + idCounter;

    }

    public Weapons(String id, String name, Integer strength, Integer dexterity, Integer intelligent, Hero hero) {
        if (this instanceof Axe) {
            this.id = Axe.class.getSimpleName() + nextId(id);
        } else if (this instanceof Bow){
            this.id = Bow.class.getSimpleName()+nextId(id);
        } else if (this instanceof Staff){
            this.id = Staff.class.getSimpleName()+nextId(id);
        }
        this.name = name;
        this.strength = strength;
        this.dexterity = dexterity;
        this.intelligent = intelligent;
        this.hero = hero;
    }

    public Weapons(String name, Integer strength, Integer dexterity, Integer intelligent, Hero hero) {
        this("", name, 10, 10, 10, null);
    }

    public Weapons(String name) {
        this("", name, 10, 10, 10, null);
    }

    public Hero getHero() {
        return hero;
    }

    public void setHero(Hero hero) {
        this.hero = hero;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setStrength(Integer strength) {
        this.strength =strength;
    }

    public int getStrength() {
        return strength;
    }

    public void setDexterity(Integer dexterity) {
        this.dexterity = dexterity;
    }

    public void setIntelligent(Integer intelligent) {
        this.intelligent = intelligent;
    }

    public int getIntelligent() {
        return intelligent;
    }

    public int getDexterity() {
        return dexterity;
    }


}
